# Workshop 6: Heating Up! Finite Difference Method
<h1 style="position: absolute; display: flex; flex-grow: 0; flex-shrink: 0; flex-direction: row-reverse; top: 60px;right: 30px; margin: 0; border: 0">
    <style>
        .markdown {width:100%; position: relative}
        article { position: relative }
    </style>
    <img src="https://gitlab.tudelft.nl/mude/public/-/raw/main/tu-logo/TU_P1_full-color.png" style="width:100px"\>
    <img src="https://gitlab.tudelft.nl/mude/public/-/raw/main/mude-logo/MUDE_Logo-small.png" style="width:100px"\>

</h1>
<h2 style="height: 10px">
</h2>

*[CEGM1000 MUDE](http://mude.citg.tudelft.nl/): Week 1.6. For: 11 October, 2023.*

## Overview
This assignment is aimed to developing an understanding the practical applications of the finite difference method. Go through the text that follows and perform all steps outlined therein.

The 1-D diffusion equation reads $$\frac{\partial u}{\partial t}=v\frac{\partial^2 u}{\partial x^2}$$
 
where $u$ is a continuous function in space and time, $v$ is a constant and often referred to as the **diffusivity**, giving rise to the name 'diffusion equation'.

In thermodynamics, the diffusion equation is referred to as the heat equation, in which, $u$ is the temperature and $v$ is the thermal diffusivity. The same equation is also found in other fields of engineering such as, the flow of groundwater through the soil, the intrusion of chemicals in a porous medium etc. Given its omnipresence in engineering, it is imperative to gain an understanding of how one can solve the diffusion equation numerically, regardless of what names we attribute to $u$ and $v$ and the underlying physical phenomenon. This is objective of today's tutorial session. 

For the time being, let's stick with thermodynamics. The rod in the sketch below, is initially at a uniform temperature of $7°C$. It is then heated asymmetrically (different temperatures) at both ends. The difference in temperatures sets up a thermal gradient, leading to the flow of heat (remember heat cannot flow without a difference in temperature). 

![assets/thermal_gradient.png](assets/thermal_gradient.png)


Now, let's use the finite difference method to obtain an accurate approximation of the temperature distribution, instead of the exact solution by:

1. Discretizing the equation in space and time to use the finite difference method.
2. Using the Taylor series to obtain an approximation for the derivatives.
3. Programming the finite difference method for the given initial and boundary conditions i.e. reformulating the differential equation as an algebraic one and solving the latter for an accurate approximation.

In each of the four Tasks below, we will use Python to solve the problem (the discretized form of the equation). In each case, you will see that we repeat the following steps:
1. Define initial conditions and boundary conditions as variables.
2. Initialize objects (i.e., Numpy arrays that represent vectors and matrices) to facilitate our computations.
3. Execute the solution (typically using a function that we define in the notebook for you).

_Are you wondering why you are doing this and why it might be relevant for your track? This is more or less how all the fancy software you will ever use works, with one exception: they make pretty buttons for you to press so that you don't have to read the source code and modify it directly._

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from ipywidgets import interact, fixed, widgets

## Task 1

First we will derive the equations for our constitutive law (heat diffusion) and solve them in 1D using the finite difference method.

<div style="background-color:#AABAB2; color: black; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>
<b>Task 1.1:</b>

Write down (on paper) the Taylor series expansion for $u_i$ around a point $i$ with a grid-size $\Delta x$ to evaluate $u_{i+1}$. Do the same to evaluate $u_{i-1}$ (up to 4 terms for both). Now, add the two Taylor expansions; do you get an equation for the second order approximation of the second derivative of $u$ with respect to $x$. For your convenience:

$$ 
\frac{\partial ^2 u}{\partial x^2}\bigg|_i = \frac{u_{i+1}-2u_i+u_{i-1}}{\Delta x^2}+O(\Delta x^2)
$$
</p>
</div>

*This assignment is not turned in for feedback, but you can insert your answers here as LaTeX equations or an image if you want to save your work for reviewing later.*

<div style="background-color:#AABAB2; color: black; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>
<b>Task 1.2:</b>
    
The left-hand side is contains a time-derivative. Let's use a counter $n$ to distinguish it from $i$. Now, write down the equation for estimating $u^{n+1}_{i}$ or the value of at location at the instance of time $t_{n+1}$ using a Taylor series expansion <b>in time</b> around $u^{n}_{i}$ for a small time-step $\Delta t$.  Round off the Taylor series to use the <b>Forward Euler</b> scheme.
 
</p>
</div>

*This assignment is not turned in for feedback, but you can insert your answers here as LaTeX equations or an image if you want to save your work for reviewing later.*

<div style="background-color:#AABAB2; color: black; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>
<b>Task 1.3:</b>   
Let's start coding the equation you obtained in Step 2 into a python code. Just to be sure you are on the right track, you should have:

$$u^{n+1}_{i}=u^n_i + v\Delta t \frac{u_{i+1}-2u_i+u_{i-1}}{\Delta x^2} $$

Define the following parameters in your code (use the picture above as a reference). We will be defining the boundary and initial conditions in this step. **Fill in the missing parts of the code.**

</p>
</div>

In [2]:
T_left = 38          # Temperature at the left
T_right = 25         # Temperature at the right
T_initial = 7       # Initial temperature of the bar
length = 300          # Length of the bar in mm
n_point = 15         # Number of points
nu = 4              # Constant value nu mm^2/s (representative value for steel)
dt = 50              # Time increment in seconds
nt = 200              # Number of time increments

dx = length/(n_point-1)
x = np.linspace(0,length,n_point)

Let's initialise the system with the initial and boundary conditions. Say $t_0 =0$.

<div style="background-color:#AABAB2; color: black; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>
Task 1.3 (continued): there are three lines you need to complete below.


</p>
</div>

In [3]:
# Initialise empty solution array "us"
us = np.zeros((nt+1,n_point))

# Initialise initial conditions into the solution array t=0
us[0] = T_initial

# Initialise boundary conditions into the solution array at t=0
# Remember that the first term is the left boundary and the last term is the right boundary.
us[0][0] = T_left
us[0][-1] = T_right

The finite difference operation will involve using an array that contains $u$ at every point in the array `x` (code), `dt`, `dx` and `nu` to return an array that contains $u$ at every point in the array `x` at the **next time step**. 

But what about the boundary points? These will remain the same as the boundaries are held at a constant temperature. Hence, for each array pertaining to $u$, the first and the last values should correspond to the boundary temperatures, before the array is used an a input for the finite difference operation. The rest of the terms can be consded as per the equation in Step 3. In short, while advancing in time, from `0` to `nt\*dt`, the first and lasts elements of the array $u$ will not be advanced in time but in fact, be assigned the boundary values of temperature. 

So if the $u$ array corresponding to the first time-step has the correct boundary values, the finite difference operation need only copy these values to their locations in every successive array in time. This can be done as an if and else statement.

In [4]:
def fdm_step(u, dx, dt, nu):

    u_new = np.zeros(len(u))

    for i in range(len(u)):

        if i == 0 or i == len(u)-1: # Exclue fixed boundary point at ends

            u_new[i] = u[i]
        else:
            u_new[i] = u[i] + nu*dt*(u[i+1] - 2*u[i] + u[i-1])/(dx**2)
            
    return u_new

<div style="background-color:#AABAB2; color: black; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>
<b>Task 1.4:</b>   

You now have the finite difference operation and initial arrays. Now write a single line of code to loop over all time steps to obtain the solution at `dt*nt`.
</p>
</div>

In [5]:
for i in range(nt):

    us[i+1] = fdm_step(us[i],dx, dt, nu)

def FDM_plot(x, u, step):
    fig = plt.figure()
    ax = plt.axes(xlim=(0, 300), ylim=(0, 40))
    ax.plot(x, u[step])
    plt.xlabel('x')
    plt.ylabel('u')
    plt.show()

play = widgets.Play(min=0, max=nt-1, step=1, value=0, interval=100, disabled=False)
slider = widgets.IntSlider(min=0, max=nt-1, step=1, value=0)
widgets.jslink((play, 'value'), (slider, 'value'))

interact(FDM_plot,
    x=fixed(x),
    u=fixed(us),
    step = (play))

widgets.HBox([slider])   

interactive(children=(Play(value=0, description='step', max=199), Output()), _dom_classes=('widget-interact',)…

<div style="background-color:#AABAB2; color: black; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>
<b>Task 1.5:</b>   

Explain what the animation above shows? Does the temperature reach a steady-state? What does that mean for heat flow?

Record your answer in the following markdown cell. 
</p>
</div>

**Write your answer here.**

## Task 2: Altering the right boundary

Say the right-end of the bar is heated with the cyclic function:
$$ u(L,t)=25+10\sin\left(\frac{2\pi t}{T}\right)$$

where $T$ is the time period of the cyclic heating. Here are the additional values for this problem.

<div style="background-color:#AABAB2; color: black; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>
<b>Task 2.1:</b>   

Based on the initialization of the problem as described in Task 1.4, can you set up the initial and boundary conditions for this situation? (you only need to change one condition).
</p>
</div>

In [6]:
t = 0
T = 6000

nt = 600
us = np.zeros((nt+1,n_point))

us[0] = T_initial

us[0][0] = T_left
us[0][-1] = 25 + 10 * np.sin(2*np.pi*t/T)

To pass on the value of the time-dependent boundary condition `T_Right` to the iteration loop, you must copy the value of `us` (the solution) to another array, modify the boundary condition on the right (which element of the array will that be?) and pass the modified array to the solution function `fdm_step`. 

You can use the following code for dynamic plotting:

In [7]:
play = widgets.Play(min=0, max=nt-1, step=1, value=0, interval=100, disabled=False)
slider = widgets.IntSlider(min=0, max=nt-1, step=1, value=0)
widgets.jslink((play, 'value'), (slider, 'value'))

interact(FDM_plot,
    x=fixed(x),
    u=fixed(us),
    step=play)

widgets.HBox([slider])

for i in range(nt):
    umod = us[i].copy()
    umod[-1] = 25 + 10*np.sin(2*np.pi*t/T)
    us[i+1] = fdm_step(umod, dx, dt, nu)
    # Update time
    t += dt


interactive(children=(Play(value=0, description='step', max=599), Output()), _dom_classes=('widget-interact',)…

<div style="background-color:#AABAB2; color: black; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>
<b>Task 2.2:</b>   

Why is the right boundary dealt with differently in the code than previously? What is different in this version compared to the first?

Record your answer in the following markdown cell. 
</p>
</div>

**Write your answer here.**

## Task 3: Extending Finite Difference Method to 2 Dimesions

![assets/2D_thermal_boundary.png](assets/2D_thermal_boundary.png)


The sketch shows a thin sheet with the boundary temperatures that are held constant. The initial uniform temperature across the sheet in shown in the centre. The sheet is a square with an edge that is $30 cm$ long. The 2-D diffusions equation reads
$$\frac{\partial u}{\partial t}=v\left(\frac{\partial^2 u}{\partial x^2}+\frac{\partial ^2 u}{\partial y^2}\right)$$

whereas, the discretised form (Forward Euler and second order approximation for the second order derivaive) reads
$$u^{n+1}_{i,j} = u^{n}_{i,j} + v\Delta t\left(\frac{u^{n}_{i,j-1}-2u^{n}_{i,j}+u^{n}_{i-1,j}}{\Delta x^2}+\frac{u^{n}_{i-1,j}-2u^{n}_{i,j}+u^{n}_{i+1,j}}{\Delta y^2}\right)$$

From the above equation, one can surmise that there are 3 changes that must be taken care of:
1. The addition of the second derivative of $u$ with respect to $y$.
2. The discrete $u$ now has 2 indices, $u_{ij}$ for the 2 directions.
3. There are 4 boundaries.

The first change requires the an addition to the update function (Part 1, Step 5). The second change implies that the solution for a time-step must now be store in a 2-D array, whereas the total solution for all time-step will be 3-D (2 dimesions for space and 1 for time). The third change requires defining 4 boundary conditions. Now, follow these steps.



<div style="background-color:#facb8e; color: black; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px"> <p>The following line removes all previous variables, which will allow us to reuse the same namespaces below without worrying about using old values on accident. We will have to re-import all of the packages.</p></div>

In [8]:
%reset

In [9]:
import numpy as np
%matplotlib inline
from ipywidgets import interact, fixed, widgets
import matplotlib.pyplot as plt
import timeit

<div style="background-color:#AABAB2; color: black; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>
<b>Task 3.1:</b>   

Let's repeat the first bit of code from Task 1. Fill in the data in the next code cell. 
</p>
</div>

<div style="background-color:#facb8e; color: black; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px"> <p>The code we have provided uses dimensions in mm, temperature in Celcius and diffusivity in length-squared per time, so mm$^2$/s.</p></div>

In [10]:
T_left_right = 38
T_top_bottom = 20
T_initial = 30
width = 300
height = 300
n_point_y = 10
n_point_x = 30
nu =  4
dt = 10
nt = 150

dx = width/(n_point_x-1)
x = np.linspace(0,width,n_point_x)
dy = height/(n_point_y-1)
y = np.linspace(0,height,n_point_y)
X, Y = np.meshgrid(x,y)

The following cell initialises the system with the initial and Dirichlet boundary conditions. 

In [11]:
us = np.zeros((nt, n_point_y, n_point_x))
us[0] = T_initial
us[0,:,0] = T_left_right
us[0,:,n_point_x-1] = T_left_right
us[0,0,:] = T_top_bottom
us[0,n_point_y-1,:] = T_top_bottom

In **Task 1**, the calculations were done using a for loop. How many for loops will you need this time? You are correct if you said two loops, a loop for x within which, there is another loop for y. Now, define the 2-D `fdm_step` as:

In [12]:
def fdm_step_2D(u, n_point_x, n_point_y, dx, dy, dt, nu):

    u_new = np.zeros((n_point_y,n_point_x))

    for i in range(n_point_y):
        for j in range(n_point_x):
            if i == 0 or i == n_point_y-1 or j == 0 or j == n_point_x-1:
                u_new[i,j] = u[i,j]        
            else:
                u_new[i,j] = u[i,j] + nu*dt*(u[i+1,j] - 2*u[i,j] + u[i-1,j])/(dy**2) + nu*dt*(u[i,j+1] - 2*u[i,j] + u[i,j-1])/(dx**2) 

    return u_new

<div style="background-color:#AABAB2; color: black; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>
<b>Task 3.2:</b>   

Now write a single line of code to call the `fdm_step_2D` function and loop it over all the time steps
</p>
</div>

In [13]:
for i in range(nt-1):
    us[i+1] = fdm_step_2D(us[i], n_point_x, n_point_y, dx, dy, dt, nu)


Use the following code to plot the results

In [14]:
def FDM_plot(x, y, us, step):
    fig = plt.figure()
    ax = plt.axes(projection='3d', xlim=(0, 300), ylim=(0, 300), zlim=(20,40))
    ax.plot_surface(x, y, us[step,:,:], cmap="magma")
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_zlabel('u')
    plt.show()

play = widgets.Play(min=0, max=nt-1, step=1, value=0, interval=100, disabled=False)
slider = widgets.IntSlider(min=0, max=nt-1, step=1, value=0)
widgets.jslink((play, 'value'), (slider, 'value'))

interact(FDM_plot,
    x=fixed(X),
    y=fixed(Y),
    us=fixed(us),
    step = play)

widgets.HBox([slider])

interactive(children=(Play(value=0, description='step', max=149), Output()), _dom_classes=('widget-interact',)…

### Task 3.2b: Vectorising the code

This is another way of doing the same thing.

A `for` loop nested inside another requires time to solve. To reduce the computational load, one can vectorise the process. This will make the code harder to understand but it will speed up the calculations, as you will later see. 

First, consider the code below:

<div style="background-color:#AABAB2; color: black; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>
<b>Task 3.2b:</b>   

Read the code below to see how this approach is different from Task 3.2, and run the cells. We will compare the results in the next Task.
</p>
</div>

In [15]:
n = 5
A = np.zeros((n,n))

for i in range(n):
    for j in range(n):
        A[i,j] = i + j*0.1

print('full matrix:')
print(A)
print('')
print('interior points:')
print(A[1:-1,1:-1])
print('')
print('right neighbors:')
print(A[1:-1,2:])
print('')

full matrix:
[[0.  0.1 0.2 0.3 0.4]
 [1.  1.1 1.2 1.3 1.4]
 [2.  2.1 2.2 2.3 2.4]
 [3.  3.1 3.2 3.3 3.4]
 [4.  4.1 4.2 4.3 4.4]]

interior points:
[[1.1 1.2 1.3]
 [2.1 2.2 2.3]
 [3.1 3.2 3.3]]

right neighbors:
[[1.2 1.3 1.4]
 [2.2 2.3 2.4]
 [3.2 3.3 3.4]]



Look for at the first row and first colum in interior points, you'll obtain the value $1.1$. Now, at the same position in right neighbours, you'll obtain $1.2$. Hence, the in full matrix, $1.2$ is the right neighbour of $1.1$. Similarly, the top neighbour of $1.1$ is $0.1$ (all indices are in Python format).

Now, let's code the vectorised function:

In [16]:
def fdm_step_2D_vectorised(u, n_point_x, n_point_y, dx, dy, dt, nu):
    u_new = np.zeros((n_point_y,n_point_x))
    u_new[1:-1, 1:-1] = (u[1:-1,1:-1] + nu * dt / dx**2 * (u[1:-1, 2:] - 2 * u[1:-1, 1:-1] + u[1:-1, 0:-2])  + nu * dt / dy**2 * (u[2:,1: -1] - 2 * u[1:-1, 1:-1] + u[0:-2, 1:-1]))
    u_new[0, :] = u[0,:]
    u_new[-1, :] = u[-1,:]
    u_new[:, 0] = u[:,0]
    u_new[:, -1] = u[:,-1]

    return u_new

Initialise an empty array 'us_vectorised' and compute the result 

In [17]:
us_vectorised = np.zeros((nt, n_point_y, n_point_x))
us_vectorised[0] = us[0]
for i in range(nt-1):
    us_vectorised[i+1] = fdm_step_2D_vectorised(us_vectorised[i], n_point_x, n_point_y, dx, dy, dt, nu)

In [18]:
play = widgets.Play(min=0, max=nt-1, step=1, value=0, interval=100, disabled=False)
slider = widgets.IntSlider(min=0, max=nt-1, step=1, value=0)
widgets.jslink((play, 'value'), (slider, 'value'))

interact(FDM_plot,
    x=fixed(X),
    y=fixed(Y),
    us=fixed(us_vectorised),
    step = play)

widgets.HBox([slider])  

interactive(children=(Play(value=0, description='step', max=149), Output()), _dom_classes=('widget-interact',)…

### Task 3.3 Using `timeit` Function

To check if the vectorised method is indeed faster to use. To do this, we use a function called `timeit`. It's purpose is to do exactly as it states, measure the time duration for a piece of code to complete. You can see how this is done in the code cell below.  

In [19]:
starttime = timeit.default_timer()

for i in range(1000): fdm_step_2D(us[0], n_point_x, n_point_y, dx, dy, dt, nu)

print(f"Time taken to perform 1000 iterations of",
      f"the explicit scheme using 2 for-loops:",
      f"{timeit.default_timer() - starttime:0.5f}\n")

starttime = timeit.default_timer() #Add a similar statement for the vectorised function

for i in range(1000): fdm_step_2D_vectorised(us_vectorised[0], n_point_x, n_point_y, dx, dy, dt, nu)

print(f"Time taken to perform 1000 iterations of",
      f"the explicit scheme using vectorisation:",
      f"{timeit.default_timer() - starttime:0.5f}\n")

Time taken to perform 1000 iterations of the explicit scheme using 2 for-loops: 0.68816

Time taken to perform 1000 iterations of the explicit scheme using vectorisation: 0.04141



<div style="background-color:#AABAB2; color: black; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>
<b>Task 3.3:</b>   

Run the code above. What can you deduce about the difference in the computational time between running two `for` loops vs vectorizing the matrices?

</p>
</div>

**Write your answer here.**

## Task 4: Altering the Boundary Condition

So far we have used Dirichlet boundary conditions, which specify the value of the independent variable at the boundary. Now, suppose the 2-D sheet problem has boundaries that are not sufficiently insulated. What does that imply? It means that the temperature at the boundary may not be held constant and there will be a net heat flux there. Heat flux is given by the derivative of $u$ with respect to $x$ or $y$. 

Hence, such a condition must be prescribed as 

$$
\frac{\partial u}{\partial x}\bigg|_w=a(x,y,t)
$$

where, $w$ is the boundary and $w$ is the normal to the boundary. This condition is called a Neumann boundary condition. In case of the 1-D problem (Part 1) on the right boundary, the above becomes

$$
\frac{\partial u}{\partial x}\bigg|_{x=L}=a
$$

which can be modified using the Taylor series expansion as:

$$
u_{i,j}=u_{i,j-1}+a\Delta x
$$

Note that the value at the boundary $u_{i,j}$ now depends on a point next to the boundary as well, $u_{i,j-1}$ (apart from the $a\Delta x$). So let's use a vectorised approach to implementing the boundary condition. The terms $a_1$ and $a_2$ in the funciton are now the boundary values at the top and the bottom boundaries of the square sheet (the left and right boundaries still have Dirichlet conditions)

In [20]:
def fdm_step_2D_Neumann(u, n_point_x, n_point_y, dx, dy, dt, nu, a1, a2):
    u_new = np.zeros((n_point_y,n_point_x))
    u_new[1:-1, 1:-1] = (u[1:-1,1:-1]
                         + nu*dt/dx**2*(u[1:-1, 2:]
                                        - 2*u[1:-1, 1:-1] 
                                        + u[1:-1, 0:-2]) 
                         + nu*dt/dy**2*(u[2:,1: -1]
                                        - 2* u[1:-1, 1:-1]
                                        + u[0:-2, 1:-1])
                        )

    u_new[0, :] = u[1,:] - a1*dy
    u_new[-1, :] = u[-2,:] + a2*dy
    u_new[:, 0] = u[:,0]
    u_new[:, -1] = u[:,-1]

    return u_new   

The rest is similar to the previous steps, initialise with the following:

<div style="background-color:#AABAB2; color: black; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px">
<p>
<b>Task 4:</b>   

Define the variables below to specify the initial conditions and boundary conditions, then run the code to find the solution.

</p>
</div>

In [21]:
T_left = 30
T_right = 30
derivative_top = 0.5    # at a1
derivative_bottom = -0.5 # at a2
T_initial = 30
width = 300
height = 100
n_point_y = 30
n_point_x = 30
nu = 4
dt = 1
nt =2000

dx = width/(n_point_x-1)
x = np.linspace(0,width,n_point_x)
dy = height/(n_point_y-1)
y = np.linspace(0,height,n_point_y)
X, Y = np.meshgrid(x,y)
us = np.zeros((nt, n_point_y, n_point_x))
us[0] = T_initial
us[0,:,0] = T_left
us[0,:,n_point_x-1] = T_right
print(us.shape)

y = np.zeros((2, 3, 4))
print(y)

(2000, 30, 30)
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


<div style="background-color:#facb8e; color: black; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px"> <p>Here is another way to visualize the plot from above in 2D, rather than a 3D perspective. It uses the dynamic plotting widget above with <code>FDM_contour</code> as the input to animate the contour plot.</p></div>

In [22]:
def FDM_contour(x, y, u, step):
    fig = plt.figure()
    ax = plt.axes(xlim=(0, 300), ylim=(0, 100))
    ax.set_aspect('equal')
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.contourf(X,Y,u[step, :, :], 200, cmap='magma')
    plt.show()

In [23]:
play = widgets.Play(min=0, max=nt-1, step=1, value=0, interval=100, disabled=False)
slider = widgets.IntSlider(min=0, max=nt-1, step=1, value=0)
widgets.jslink((play, 'value'), (slider, 'value'))

interact(FDM_contour,
    x=fixed(X),
    y=fixed(Y),
    u=fixed(us),
    step = play)

widgets.HBox([slider])

interactive(children=(Play(value=0, description='step', max=1999), Output()), _dom_classes=('widget-interact',…

<div style="background-color:#facb8e; color: black; vertical-align: middle; padding:15px; margin: 10px; border-radius: 10px"> <p>Hopefully, you are able to use this notebook to gain some experience into how finite difference methods can be utilized to help model systems like this heat conduction example. These concepts will be expanded later in the module as we extend these concept into finite volume and finite element modelling. </p></div>

**End of notebook.**
<h2 style="height: 60px">
</h2>
<h3 style="position: absolute; display: flex; flex-grow: 0; flex-shrink: 0; flex-direction: row-reverse; bottom: 60px; right: 50px; margin: 0; border: 0">
    <style>
        .markdown {width:100%; position: relative}
        article { position: relative }
    </style>
    <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">
      <img alt="Creative Commons License" style="border-width:; width:88px; height:auto; padding-top:10px" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" />
    </a>
    <a rel="TU Delft" href="https://www.tudelft.nl/en/ceg">
      <img alt="TU Delft" style="border-width:0; width:100px; height:auto; padding-bottom:0px" src="https://gitlab.tudelft.nl/mude/public/-/raw/main/tu-logo/TU_P1_full-color.png"/>
    </a>
    <a rel="MUDE" href="http://mude.citg.tudelft.nl/">
      <img alt="MUDE" style="border-width:0; width:100px; height:auto; padding-bottom:0px" src="https://gitlab.tudelft.nl/mude/public/-/raw/main/mude-logo/MUDE_Logo-small.png"/>
    </a>
    
</h3>
<span style="font-size: 75%">
&copy; Copyright 2023 <a rel="MUDE Team" href="https://studiegids.tudelft.nl/a101_displayCourse.do?course_id=65595">MUDE Teaching Team</a> TU Delft. This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.